apiVersion: v1
kind: Service
metadata:
  name: api-rof
spec:
  selector:
    app: api-rof
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rof
  template:
    metadata:
      labels:
        app: api-rof
    spec:
      containers:
        - name: api-rof
          image: mogador26/api-rof:1.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-rof           # The ConfigMap this value comes from.
                  key: port 
            - name: WINDOW_TIME
              valueFrom:
                configMapKeyRef:
                  name: api-rof           # The ConfigMap this value comes from.
                  key: window_time 
            - name: MAX_REQUEST_BY_IP
              valueFrom:
                configMapKeyRef:
                  name: api-rof           # The ConfigMap this value comes from.
                  key: max_request_by_ip 
            - name: LIMIT_SEARCH
              valueFrom:
                configMapKeyRef:
                  name: api-rof           # The ConfigMap this value comes from.
                  key: limit_search 
            - name: URL_DB
              valueFrom:
                secretKeyRef:
                  name: api-rof-secret
                  key: URL_DB
              #value: mongodb://mongo:27017/rof-bd
          imagePullPolicy: Always
