apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose-sans-web.yml
    kompose.version: 1.26.0 (40646f47)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
    - name: "28000"
      port: 28000
      targetPort: 28000
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
