apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.2-focal
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rof-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rof-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB
              valueFrom:
                secretKeyRef:
                  name: rof-secret
                  key: MONGO_INITDB
            - name: MONGO_USERNAME_DB
              valueFrom:
                secretKeyRef:
                  name: rof-secret
                  key: MONGO_USERNAME_DB
            - name: MONGO_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: rof-secret
                  key: MONGO_PASSWORD_DB
          volumeMounts:
            - name: mongodb-configuration-file
              mountPath: /etc/mongod.conf
              readOnly: true
            - name: storage
              mountPath: /data/db
            
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongodb-configuration-file
          configMap:
            name: mongodb-config-file