version: "3.5"
services:
  mongodb:
    container_name: mongo
    image: mongo:${MONGODB_VERSION:-4.0}
    restart: always
    volumes:
      - data-rof:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: rof-bd
      MONGO_USERNAME_DB: admin
      MONGO_PASSWORD_DB: secret
    ports:
      - "27017:27017"
    networks:
      - storage
  api-rof:
    container_name: api-rof
    image: api-rof:1.0
    restart: always
    environment:
      PORT: 3000
      WINDOW_TIME: 900000
      MAX_REQUEST_BY_IP: 100
      URL_DB: "mongodb://admin:secret@mongodb:27017/rof-bd?retryWrites=true&w=majority"
      LIMIT_SEARCH: 10
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - storage
networks:
  storage:
volumes:
  data-rof:
