# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
   PORT: 8000
   WINDOW_TIME: 900000
   MAX_REQUEST_BY_IP: 100
   URL_DB: "mongodb+srv://${{ secrets.USER_DB_ATLAS }}:${{ secrets.PASS_DB_ATLAS }}@${{secrets.URL_DB_ATLAS }}"
   LIMIT_SEARCH: 10

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run dev &
    - run: |
          ps -ef | grep node
          sudo apt-get install curl
          sudo apt-get install jq
          curl "http://localhost:8000/api/v1/operateurs_funeraires/healthcheck" | jq .etat
