# This is a basic workflow to help you get started with Actions

name: CI/CD - Heroku with healthcheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          cat << EOF > .env
          PORT=6000
          WINDOW_TIME=900000
          MAX_REQUEST_BY_IP=100
          URL_DB="mongodb+srv://${{ secrets.USER_DB_ATLAS }}:${{ secrets.PASS_DB_ATLAS }}@${{ secrets.URL_DB_ATLAS }}"
          EOF
        
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"
          heroku_email: "${{ secrets.HEROKU_EMAIL }}"
          env_file: ".env"
          region: eu
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api/v1/operateurs_funeraires/healthcheck"
          delay: 5
          dontuseforce: false
