name: Artillery API ROF Load Test

on:
  push:
    branches:
      - master
  
  workflow_dispatch:    
  schedule:
    - cron: '0 0 * * *'
jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        

      - name: Make reports directory
        run: mkdir reports

      - name: Execute load tests
        run: /home/node/artillery/bin/artillery run --output reports/report.json test/api_rof.yaml

      - name: Generate HTML report
        run: /home/node/artillery/bin/artillery report --output reports/report reports/report.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*
          retention-days: 5
